trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'sc-td2tier-terraform'

steps:

# Install the same Terraform version used locally
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.16.2'

# Login to Azure using the Azure DevOps service connection
- task: AzureCLI@2
  displayName: 'Terraform Init, Validate and Plan'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init -input=false

      terraform validate

      terraform plan -input=false